[package]
name = "kan-ban-jam-file"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
env_home = "0.1.0"
regex = "1.11.0"
warp = "0.3.7"
futures-util = "0.3.30"