[package]
name = "kan-ban-jam-file"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
serde_json = "1.0.127"
serde = { version = "1", features = ["derive"] }
uuid = "1.10.0"
rand = "0.8.5"
tokio = "1.40.0"