[package]
name = "kan-ban-jam-file"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.127"
env_home = "0.1.0"
regex = "1.10.6"
warp = "0.3"
futures-util = "0.3.30"